version: '3'
services:
  app:
    container_name: "SecretariAI-app"
    build: ./build/app/
    volumes:
      - ./app:/app
    env_file:
      - ./build/app/.node_env
      - ./build/app/.node_env_secret
    ports:
    - 3000:3000
    tty: true
    init: true
    depends_on:
      - voicebox
  voicebox:
    container_name: "SecretariAI-voicebox"
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
    - 50021:50021
    tty: true
    init: true